version: '3'
services:
  #############################################
  ##            ZEND_API                 ##
  #############################################
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      PORT : 3000
      DATABASE_URL: "postgresql://postgres:123@db:5432/nestjs?schema=public" 
    depends_on:
    - db
    
  #############################################
  ##            ZEND_POSTGRES             ##
  #############################################
  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nestjs
      
 